### ISSUE TITLE
Friends menu is broken

### ISSUE THREAD

**Issue by deveers** [hyoretsu/Ultimate-Steam-Dark-Mode-Skin#3]
![image](https://user-images.githubusercontent.com/98456024/187057269-2b9ce914-602f-432c-a7c2-14f9417f1856.png)

**Comment by hyoretsu** [comment]
You tried resetting Steam and re-applying the skin, correct?

**Comment by deveers** [comment]
I did that and it went back to the default one
![image](https://user-images.githubusercontent.com/98456024/187236330-2b98fcab-6174-45d6-a47e-dd0d2fdbafbf.png)

**Comment by hyoretsu** [comment]
Try moving the files in `clientui` folder and re-applying the patch

**Comment by deveers** [comment]
Reinstalled steam from scratch and redid the entire thing

can confirm it's fine now

also, thanks for the skin!

![image](https://user-images.githubusercontent.com/98456024/187251882-26ecf665-5abe-47da-ad0d-5aeed523bdfb.png)
